name: Branch Name

on:
  push:
    branches: [*]

jobs:
  build:
    name: Build Staging Image
    runs-on: ubuntu-latest

    steps:
       steps:
        - uses: actions/checkout@v1
        - run: npm ci
        - uses: nelonoel/branch-name@v1.0.1
        - run: echo ${BRANCH_NAME}
