name: Branch Name

on:
  push:
    branches: ['*', '*/*']

jobs:
  build:
    name: Build Staging Image
    runs-on: ubuntu-latest
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4    
      - name: Coba
        run: echo ${GITHUB_REF_SLUG}
