name: Branch Name

on:
  push:
    branches: ['*', '*/*']

jobs:
  build:
    name: Build Staging Image
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})" | iconv -t ascii//TRANSLIT | sed -r s/[~\^]+//g | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-z
        id: extract_branch
      - name: Coba
        run: echo ${{ steps.extract_branch.outputs.branch }}
