name: Branch Name

on:
  push:
    branches: ['*']

jobs:
  build:
    name: Build Staging Image
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Coba
        run: echo ${{ steps.extract_branch.outputs.branch }}
